[package]
name = "pdfzf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
inline_colorization = "0.1.6"
lopdf = { version = "0.34.0", features = ["pom", "pom_parser"] }
nucleo = "0.5.0"
rayon = "1.10.0"
